# Generated by Django 5.2.6 on 2025-09-12 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20, verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'unité et quantité',
                'verbose_name_plural': 'unités et quantités',
                'ordering': ('unit',),
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.quantityunit', verbose_name='Quantité'),
        ),
    ]
