# Generated by Django 5.2.6 on 2025-09-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_quantityunit_remove_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='quantityunit',
            options={'ordering': ('unit',), 'verbose_name': 'unité', 'verbose_name_plural': 'unités'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ingredient', verbose_name='Ingrédient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='App.recipe', verbose_name='Recette')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.quantityunit', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'ingrédient de recette',
                'verbose_name_plural': 'ingrédients de recette',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
