# Generated by Django 5.2.6 on 2025-09-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_recipe_category_alter_quantityunit_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuantityUnit',
            new_name='Unit',
        ),
    ]
