# Generated by Django 5.2.6 on 2025-09-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_quantityunit_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(default='', upload_to='ingredients/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='', upload_to='recipes/', verbose_name='Image'),
        ),
    ]
