# Generated by Django 5.2.6 on 2025-09-26 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_recipe_image_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='ingredients/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.unit', verbose_name='Unité'),
        ),
    ]
