# Generated by Django 5.2.6 on 2025-10-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_fr_ca',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_fr_ca',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions_en',
            field=models.TextField(null=True, verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions_fr_ca',
            field=models.TextField(null=True, verbose_name='Instructions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_fr_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Unité'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_fr_ca',
            field=models.CharField(max_length=20, null=True, verbose_name='Unité'),
        ),
    ]
